failing tests for empty unsub and punsub
When unsubscribe or punsubscribe is called
and there is nothing to unsubscribe from, the reply[1]
argument is a null which causes a TypeError
Cannot call method 'toString' of null

```
TypeError: Cannot call method 'toString' of null
    at RedisClient.return_reply (/Users/barczewskij/projects/node_redis/index.js:633:65)
    at ReplyParser.RedisClient.init_parser (/Users/barczewskij/projects/node_redis/index.js:266:14)
    at ReplyParser.EventEmitter.emit (events.js:96:17)
    at ReplyParser.send_reply (/Users/barczewskij/projects/node_redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/Users/barczewskij/projects/node_redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/Users/barczewskij/projects/node_redis/index.js:483:27)
    at Socket.<anonymous> (/Users/barczewskij/projects/node_redis/index.js:82:14)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:396:14)
```

Conflicts:

	test.js